### ISSUE TITLE
Error occurred when using the model to find the melody in pickled file

### ISSUE THREAD

**Issue by sophia1488** [2019paper/Symbolic-Melody-Identification#1]
Hi, I'd like to reproduce your result.
But when I run this command `./terminal_client.py --model nn_kernels_mozart.pkl --extract mozart/kv279_2.pyc.bz output.mid`, an error occurred on line 315 `WIN_WIDTH = network.win_width`, stating that 'list' object has no attribute 'win_width'.
It seems that the format of the model is array, while the code expected it to be an object?

**Comment by 00sapo** [comment]
Hello, I'm happy that you're interested in this work! It's been a long time since I don't use this code, but let's try to solve the issue.

This code is a little old and written using `lasagne` and `theano` which are both outdated now. The list of kernels provided is a python object that should be used to compile your model on your architecture. This is needed because, as far as I know, theano needed to recompile the mdel on each different architecture before of using it (e.g. cpu x64, cpu x32, gpu, etc). This is a bit strange for people used to modern framework like pytorch, but it allowed for good (and perhaps better) numeric and computational optimizations. 

So, if I understand correctly your issue, you should first compile the model... see [here](https://limunimi.github.io/Symbolic-Melody-Identification/usage/): 

```
./terminal_client.py --rebuild kernels.pck parameters.json model.pkl
```

Then, you can use your model to extract melodies:

```
./terminal_client.py --model model.pkl --extract file.mxl output.mid
```

**Comment by sophia1488** [comment]
Thank you for your reply!

But compiling the model requires the kernels saved in kernels.pkl, I assume that the command to train over all files with extension .ext in mydirectory using hyper-parameters contained in parameters.json (saves kernels to a pickle object) is also needed?
`./terminal_client.py --train mydirectory .ext parameters.json`

Are the files (.ext) available so that I can run this command? I can't find them in your repo.

I appreciate your help!

**Comment by 00sapo** [comment]
To build the model you need the kernel parameters and the network hyper-parameters. The network hyper parameters can be found, if you want, using hyer-parameter optimization. You can also find new kernels by training the network on a dataset. Part of the dataset that we could redistribute is in the `data` directory compressed in `xz` format. You should uncompress it first.

By the way, our hyper-parameters and kernels are distributed in root folder of the git project: `cnn_parameters.json` (hyper-parameters), `nn_kernels_pop.pkl` (kernels trained on the pop dataset) and `nn_kernels_mozart.pkl` (kernels trained on the mozart dataset). So, you can rebuild the model using these trained kernels/hyper-parameters and then test the model on any song.

Ciao,
f
